#ifndef _COCONUT_MILK_GRAPHICS_DX11_SHADERTYPE_HPP_
#define _COCONUT_MILK_GRAPHICS_DX11_SHADERTYPE_HPP_

#include <string>

namespace coconut {
namespace milk {
namespace graphics {

enum class ShaderType {
	VERTEX,
	PIXEL
};

// TODO: we want these generated by some enum tool probably (or refactored)
const std::string& toString(ShaderType shaderType);
void fromString(ShaderType& shaderType, const std::string& name);

} // namespace graphics
} // namespace milk
} // namespace coconut

#endif /* _COCONUT_MILK_GRAPHICS_DX11_SHADERTYPE_HPP_ */
